/**
 * Zod Emitter
 * Amano-Project コンパイラの IR から Zod スキーマを生成するエミッタ
 *
 * 生成されるコードは TypeScript (zod) のスキーマ定義および infer 型を含む。
 */

const indent = (level) => "  ".repeat(level);

class ZodEmitter {
  /**
   * メインエントリポイント
   * IR（entities, relations, fields など）を受け取り、Zod スキーマ文字列を生成する
   */
  emit(ir) {
    const entitySchemas = [];
    const entityTypes = [];

    // 循環参照に対応するため、まずスキーマ変数のみ宣言
    for (const entity of ir.entities) {
      entitySchemas.push(`export const ${entity.name}Schema = z.lazy(() => z.object({`); // 内容は後で閉じる
    }

    // 実際のフィールド内容を埋める
    const fieldsCode = ir.entities.map((entity) => {
      const lines = [];
      for (const field of entity.fields) {
        lines.push(`${indent(2)}${field.name}: ${this.mapFieldToZod(field)},`);
      }
      return {
        name: entity.name,
        body: lines.join("\n")
      };
    });

    // スキーマを完成
    const finishedSchemas = fieldsCode.map((ent) => {
      return (
        `export const ${ent.name}Schema = z.lazy(() => z.object({\n` +
        ent.body +
        `\n}));`
      );
    });

    // TypeScript 型推論
    for (const entity of ir.entities) {
      entityTypes.push(
        `export type ${entity.name} = z.infer<typeof ${entity.name}Schema>;`
      );
    }

    // すべて統合
    return (
      `// Zod Schema (Generated by Amano-Project Compiler)\n` +
      `import { z } from "zod";\n\n` +
      finishedSchemas.join("\n\n") +
      "\n\n" +
      entityTypes.join("\n")
    );
  }

  /**
   * フィールド単位で Zod スキーマを返す
   * @param {*} field
   * @returns 字句レベルでの Zod 定義文字列
   */
  mapFieldToZod(field) {
    // リレーション：配列
    if (field.isRelation && field.type.endsWith("[]")) {
      const ent = field.type.replace("[]", "");
      return `z.array(z.lazy(() => ${ent}Schema))${field.isNullable ? ".nullable()" : ""}`;
    }

    // リレーション：単数
    if (field.isRelation) {
      const ent = field.type;
      return `z.lazy(() => ${ent}Schema)${field.isNullable ? ".nullable()" : ""}`;
    }

    // プリミティブ型
    let base = this.mapPrimitive(field.type);

    if (field.isNullable) {
      base += ".nullable()";
    }
    return base;
  }

  /**
   * DSL のプリミティブ型を Zod 型へマッピング
   */
  mapPrimitive(type) {
    switch (type) {
      case "Int":
      case "Float":
      case "Number":
        return "z.number()";
      case "String":
        return "z.string()";
      case "Boolean":
        return "z.boolean()";
      case "DateTime":
        return "z.string().datetime()";
      case "UUID":
        return "z.string().uuid()";
      default:
        return "z.any() /* Unknown type */";
    }
  }
}

module.exports = {
  ZodEmitter
};
