// zod-emitter.js
//
// Amano-Project: Zod Emitter
// -------------------------
// IR から Zod スキーマと TypeScript 型定義を生成するエミッタ。
// 仕様:
//  - 各エンティティについて z.object({ ... }) を生成
//  - リレーションフィールドには z.lazy を使用
//  - 配列リレーションは z.array(z.lazy(...))
//  - IR の metadata（isNullable, isUnique）は Zod で表現できない部分はコメントに出力
//  - 生成結果は単一の TypeScript ファイルとして返す
//
// 出力例（User, Post の2エンティティの場合）:
//   import { z } from "zod";
//   export const UserSchema = z.object({ ... });
//   export type User = z.infer<typeof UserSchema>;
//
// このエミッタはコンパイラ (src/compiler/index.js) から
//   emitter.emit(ir)
// の形式で呼び出される。

class ZodEmitter {
  constructor() {}

  /**
   * IR を受け取り、Zod スキーマ + TS 型定義の TypeScriptコードを返す
   * @param {object} ir - 中間表現（canonicalizer の出力）
   * @returns {string} TypeScript コード
   */
  emit(ir) {
    const lines = [];

    // ----------------------------
    // ヘッダーコメント & import
    // ----------------------------
    lines.push(`// --------------------------------------------`);
    lines.push(`// Auto-generated by Amano-Project Zod Emitter`);
    lines.push(`// DO NOT EDIT MANUALLY`);
    lines.push(`// --------------------------------------------`);
    lines.push(`import { z } from "zod";`);
    lines.push("");

    // ----------------------------------------------------
    // 1. まず entity 名だけを収集し、lazy 参照のためのセットを作る
    // ----------------------------------------------------
    const entityNames = ir.entities.map(e => e.name);

    // ----------------------------------------------------
    // 2. 各エンティティの Zod スキーマ本体を生成
    // ----------------------------------------------------
    for (const entity of ir.entities) {
      const schemaName = `${entity.name}Schema`;

      lines.push(`// --------------------------------------------`);
      lines.push(`// ${entity.name} Schema`);
      lines.push(`// --------------------------------------------`);

      // フィールド生成
      const fieldLines = [];

      for (const field of entity.fields) {
        const zodExpr = this._mapFieldToZod(field, entityNames);
        const comment = this._makeFieldComment(field);

        fieldLines.push(`  ${field.name}: ${zodExpr},${comment}`);
      }

      lines.push(`export const ${schemaName} = z.object({`);
      lines.push(fieldLines.join("\n"));
      lines.push(`});`);
      lines.push("");

      // TypeScript 型
      lines.push(`export type ${entity.name} = z.infer<typeof ${schemaName}>;`);
      lines.push("");
    }

    return lines.join("\n");
  }

  // ------------------------------------------------------------
  // フィールドを Zod 式に変換する
  // ------------------------------------------------------------
  _mapFieldToZod(field, entityNames) {
    const { type, isNullable } = field;

    // 配列・リレーション判定
    const isArrayRelation = type.endsWith("[]");
    const baseType = isArrayRelation ? type.replace("[]", "") : type;

    // リレーション（ユーザ定義エンティティ）
    if (entityNames.includes(baseType)) {
      const lazyRef = `z.lazy(() => ${baseType}Schema)`;
      let expr = isArrayRelation ? `z.array(${lazyRef})` : lazyRef;
      if (isNullable) expr += `.nullable()`;
      return expr;
    }

    // プリミティブ型
    let zodType = this._mapPrimitiveTypeToZod(baseType);

    if (isNullable) zodType += `.nullable()`;
    return zodType;
  }

  // ------------------------------------------------------------
  // プリミティブ型マッピング
  // ------------------------------------------------------------
  _mapPrimitiveTypeToZod(type) {
    switch (type) {
      case "Int":
      case "Float":
        return "z.number()";

      case "String":
        return "z.string()";

      case "Boolean":
        return "z.boolean()";

      case "UUID":
        return "z.string().uuid()";

      case "DateTime":
        return "z.string().datetime()";

      default:
        return "z.any() // Unknown type";
    }
  }

  // ------------------------------------------------------------
  // isUnique, isRelation など Zod に直接反映できない情報はコメントとして残す
  // ------------------------------------------------------------
  _makeFieldComment(field) {
    const notes = [];

    if (field.isUnique) notes.push(" unique");
    if (field.isRelation) notes.push(" relation");

    return notes.length > 0 ? ` //${notes.join(",")}` : "";
  }
}

module.exports = {
  ZodEmitter,
  emit: (ir) => new ZodEmitter().emit(ir)
};
